Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,10 @@
 name: Generate Pac-Man Game
 
 on:
-  schedule: # Run automatically every 24 hours
-    - cron: "0 */24 * * *"
-  workflow_dispatch: # Allows manual triggering
-  push: # Runs on every push to the main branch
+  schedule:
+    - cron: "0 2 * * *"  # Каждый день в 2:00 ночи UTC
+  workflow_dispatch:
+  push:
     branches:
       - main
 
@@ -16,12 +16,25 @@ jobs:
     timeout-minutes: 5
 
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Clean output directory
+        run: rm -rf dist && mkdir -p dist
+
       - name: Generate pacman-contribution-graph.svg
         uses: abozanona/pacman-contribution-graph@main
         with:
           github_user_name: ${{ github.repository_owner }}
+        continue-on-error: true
 
-      # Push the generated SVG to the output branch
+      - name: Check SVG exists
+        run: |
+          if [ ! -f dist/pacman-contribution-graph.svg ]; then
+            echo "SVG not found. Exiting..."
+            exit 1
+          fi
+
       - name: Push pacman-contribution-graph.svg to the output branch
         uses: crazy-max/ghaction-github-pages@v2.1.3
         with:
